/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Apple window title bar
 #	author : miyako
 #	2018/05/28
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Apple window title bar

		case 1 :
			HIDE_WINDOW_TITLE_BAR(pResult, pParams);
			break;

	}
}

#pragma mark -

WindowRef PA_GetWindowRef(int winId)
{
	return (WindowRef)PA_GetWindowPtr(reinterpret_cast<PA_WindowRef>(winId));
}

NSWindow *PA_GetWindowRef64(int winId)
{
	//EX_GET_HWND has been fixed in 15R3 to return a NSWindow* on mac 64bit.
	//http://forums.4d.fr/Post/EN/15872830/1/17032044
	
	PA_ulong32 version = (PA_Get4DVersion() & 0x0000FFFF);
	//	int minor = version & 0x000F;
	int r = (version & 0x00F0) >> 4;
	int major = (version & 0xFF00) >> 8;
	if (((major >=0x15) && (r >= 3)) || (major >=0x16))
	{
		return (NSWindow *)PA_GetWindowPtr(reinterpret_cast<NSWindow *>(winId));
	}
	return 0;
}

NSWindow *getWindow(C_LONGINT &Param)
{
	return PA_GetWindowRef64(Param.getIntValue());
}

#pragma mark -

// ---------------------------- Apple window title bar ----------------------------


void HIDE_WINDOW_TITLE_BAR(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT Param1;

	Param1.fromParamAtIndex(pParams, 1);

#if CGFLOAT_IS_DOUBLE
	NSWindow *window = getWindow(Param1);
	[window setTitleVisibility:NO];
	[window setStyleMask:[window styleMask]|NSFullSizeContentViewWindowMask];
	[window setTitlebarAppearsTransparent:YES];
#endif
}

