/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Apple window title bar
 #	author : miyako
 #	2018/05/28
 #
 # --------------------------------------------------------------------------------*/



// --- Apple window title bar
void HIDE_WINDOW_TITLE_BAR(sLONG_PTR *pResult, PackagePtr pParams);
