/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Apple-window-title-bar.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Apple window title bar
 #	author : miyako
 #	2020/11/27
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Apple-window-title-bar.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Apple window title bar
            
			case 1 :
                PA_RunInMainProcess((PA_RunInMainProcessProcPtr)HIDE_WINDOW_TITLE_BAR, params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void HIDE_WINDOW_TITLE_BAR(PA_PluginParameters params) {

    PA_long32 arg1 = PA_GetLongParameter(params, 1);
    
    NSWindow *window = reinterpret_cast<NSWindow *>(PA_GetWindowPtr(reinterpret_cast<PA_WindowRef>(arg1)));
    
    if(window) {
        
        if ([window respondsToSelector:@selector(setTitleVisibility:)]) {
            [window setTitleVisibility:NSWindowTitleHidden];
        }

        [window setStyleMask:[window styleMask]|NSFullSizeContentViewWindowMask];
        [window setTitlebarAppearsTransparent:YES];
          
    }
    
}

