/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Apple-window-title-bar.h
 #	source generated by 4D Plugin Wizard
 #	Project : Apple window title bar
 #	author : miyako
 #	2020/11/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_APPLE_WINDOW_TITLE_BAR_H
#define PLUGIN_APPLE_WINDOW_TITLE_BAR_H

#include "4DPluginAPI.h"

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#endif

#pragma mark -

static void HIDE_WINDOW_TITLE_BAR(PA_PluginParameters params);

#endif /* PLUGIN_APPLE_WINDOW_TITLE_BAR_H */
